# Generated by Django 2.2 on 2020-10-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_post',
            new_name='date_posted',
        ),
    ]
